### ISSUE TITLE
Fix average / max abundance

### ISSUE THREAD

**Issue by anderaa** [anderaa/BioEcon_Knobel#1]
Is average and max abundance calculated based on all dogs or just dogs born after 1/1/2012? It should be based on all dogs.

**Comment by jcnavin** [comment]
Right now, both are calculated based on dogs who enter the population on or after 1/1/2012,  not necessarily if they are born after that. There are a disproportionate amount of dogs entering the population after 2011 relative to before 2011 (much more recorded from 2011 onward), if we were to include all dogs and check each day a dog is alive we would most likely be understating both of the parameters, due to recording bias.

**Comment by anneconan** [comment]
Hi. To explain, the high number of entry in 2011: the first census of the study has been done in 2011. the day of the observation of the dog was considered as the "entry" in the population. The dogs written as entered before 2011 are dogs who were not recorded during this first census but during one of the following visit. Then the entry data was estimate by the owner. These is why we start all our analyses from 2012.

**Comment by anderaa** [comment]
Jordan, we want all the dogs in this one. Since we just want mean abundance or max abundance, we don't care when the dogs 'entered'.

**Comment by jcnavin** [comment]
Yes, however my ? is if we are looking at this on a daily level, should I be including all dogs regardless of entry date but only counting days from 1/1/2012 onward?

**Comment by anderaa** [comment]
Oh right - excellent question. All dogs, but lets count abundance only within 2012-2015. So also throw out the days in 2016.

**Comment by jcnavin** [comment]
Thank you.  I am currently running the script that addresses this issue. All dogs are included that enter after the minimum entry date we have information on, the sample is then limited to 2012-2015 and the associated parameters are calculated.

**Comment by anderaa** [comment]
We're only talking about mean/max abundance right?

**Comment by jcnavin** [comment]
The changes were made to the script that calculates max/mean abundance, and average percentage of the population that are female/juvenile. I haven't pushed yet (its still running we have a ton of observations), should this change only be applied to mean/max abundance and not the other two calculations?

**Comment by jcnavin** [comment]
Fixed calculation of mean/max abundance as discussed above, added average percentage of total population that are puppies (age <90 days) to Script3_A.R
