### ISSUE TITLE
Litter count by month

### ISSUE THREAD

**Issue by anderaa** [anderaa/BioEcon_Knobel#6]
Need a count of litters by month. Count only litters born 1/1/2012 - 12/31/2015. But make sure that it includes litters born to any female - even those females that entered before 1/1/2012.

**Comment by jcnavin** [comment]
Do we want litters for each month by year, or all litters that happened in a given month during the specified time period?

**Comment by jcnavin** [comment]
Should we be calculating average litter size in a similar manner? That is, including all female dogs regardless of entry date where sufficient information exists, but only looking at litters had during the time period 1/1/2012-12/31/2015?

**Comment by anderaa** [comment]
Yes.

**Comment by jcnavin** [comment]
Fixed calculation of average litter size as discussed above and added a litter count by month for the specified time frame in Script2_D.R
